FisCompendium.Web/Controllers/CombatController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace FisCompendium.Web.Controllers
{
    [Authorize("IsQM")]
    public class CombatController : Controller
    {
        public IActionResult Error()
        {
            return View();
        }

        [Authorize("IsQM")]
        public IActionResult Grid()
        {
            return View();
        }

        [Authorize("IsQM")]
        public IActionResult Tools()
        {
            return View();
        }
    }
}

FisCompendium.Web/Controllers/PermissionsController.cs
using FisCompendium.Web.Extensions;
using FisCompendium.Web.Models.Account;
using FisCompendium.Web.Utilities;
using FisCompendium.Web.Utilities.UserData.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace FisCompendium.Web.Controllers
{
    [Authorize("IsQM")]
    public class PermissionsController : Controller
    {
        public IUserPermissionLookup UserPermissionsLookup { get; }

        public PermissionsController(IUserPermissionLookup userLookup)
        {
            UserPermissionsLookup = userLookup;
        }

        public IActionResult Error()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Update()
        {
            var users = UserPermissionsLookup.GetUserPermissions();
            ViewData["Users"] = users;
            return View();
        }

        [HttpPost]
        public IActionResult Update(AccountPermission model)
        {
            if (!ModelState.IsValid)
            {
                TempData.AddError("Please correct validation errors.");
                return View();
            }

            UserPermissionsLookup.UpdatePermissionFor(model.Username, model.PermissionsLevel);
            return Update();
        }
    }
}

FisCompendium.Web/Controllers/QMMapsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace FisCompendium.Web.Controllers
{
    [Authorize("IsQM")]
    public class QMMapsController : Controller
    {
        public IActionResult Error()
        {
            return View();
        }

        [Authorize("IsQM")]
        public IActionResult World()
        {
            return View();
        }
    }
}

FisCompendium.Web/Controllers/QMNotesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Security.Claims;
using System.Text.RegularExpressions;
using FisCompendium.Data.Game_Data;
using FisCompendium.Data.User_Data;
using FisCompendium.Repository;
using FisCompendium.Web.Extensions;
using FisCompendium.Web.Utilities.GameData.Knowledge;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace FisCompendium.Web.Controllers
{
    [Authorize("IsQM")]
    public class QMNotesController : Controller
    {
        private IQMNoteRepository Repository { get; }

        public QMNotesController(IQMNoteRepository repository)
        {
            Repository = repository;
        }

        [Authorize("IsQM")]
        public IActionResult Error() => View();

        [Authorize("IsQM")]
        public IActionResult Index([FromQuery]bool showAll)
        {
            var index = Repository.GetIndex(showAll);
            return View(index);
        }

        [Authorize("IsQM")]
        public IActionResult Item([FromQuery] string itemId, [FromQuery] string title = "")
        {
            if (!Guid.TryParse(itemId, out var id))
            {
                TempData.AddError("Id could not be parsed.");
                return RedirectToAction("Index");
            }

            var data = Repository.GetById(id);
            if (data == null)
            {
                TempData.AddError("Item not found.");
                return RedirectToAction("Index");
            }

            data.Notes = ParseLinks(data.Notes);

            return View("Item", data);
        }

        private IEnumerable<string> GetSubStrings(string input, string start, string end)
        {
            Regex r = new Regex(Regex.Escape(start) + "(.*?)" + Regex.Escape(end));
            MatchCollection matches = r.Matches(input);
            foreach (Match match in matches)
                yield return match.Groups[1].Value;
        }

        private string ParseLinks(string input)
        {
            if (string.IsNullOrEmpty(input)) return input;
            var replacements = GetSubStrings(input, "[[", "]]")
                .Select(x => $"[[{x}]]")
                .ToList();
            if (!replacements.Any()) return input;

            string output = input + "";
            foreach (var replacement in replacements)
            {
                var title = replacement.Replace("[[", "").Replace("]]", "");
                var id = Repository.GetItemId(title);

                if (id == Guid.Empty)
                {
                    var url = Url.Action("NewByTitle");
                    var html = $"<a href='{url}?title={WebUtility.UrlEncode(title)}' style='color: red' target='_blank'>{title}</a>";
                    output = output.Replace(replacement, html);
                }
                else
                {
                    var url = Url.Action("Item");
                    var html = $"<a href='{url}?itemId={id}'>{title}</a>";
                    output = output.Replace(replacement, html);
                }
            }

            return output;
        }

        [Authorize("IsQM")]
        public IActionResult NewByTitle([FromQuery] string title)
        {
            SetTags();

            return View("New", new QMNote
            {
                Title = title,
            });
        }

        [Authorize("IsQM")]
        public IActionResult New(QMNote model)
        {
            SetTags();

            if (model == null)
            {
                model = new QMNote();
                return View(model);
            }

            if (!ModelState.IsValid)
            {
                TempData.AddError("Please correct validation errors.");
                return View(model);
            }

            var id = Repository.Create(model);
            if (id == Guid.Empty)
            {
                TempData.AddError("An error occurred while creating the item.");
                return View(model);
            }

            TempData.AddMessage("Item created successfully.");
            return RedirectToAction("Item", new {itemId = id.ToString()});
        }

        [Authorize("IsQM")]
        public IActionResult Edit([FromQuery] string itemId)
        {
            SetTags();

            if (!Guid.TryParse(itemId, out var id))
            {
                TempData.AddError("Id could not be parsed.");
                return RedirectToAction("Index");
            }

            var data = Repository.GetById(id);
            if (data == null)
            {
                TempData.AddError("Item not found.");
                return RedirectToAction("Index");
            }

            return View(data);
        }

        [Authorize("IsQM")]
        public IActionResult SubmitEdit(QMNote model)
        {
            SetTags();

            if (!ModelState.IsValid)
            {
                TempData.AddError("Please correct validation errors.");
                return View("Edit", model);
            }

            var data = Repository.GetById(model.QMNoteId);
            if (data == null)
            {
                TempData.AddError("Item not found.");
                return RedirectToAction("Index");
            }


            var success = Repository.Edit(model);
            if (!success)
            {
                TempData.AddError("An error occurred while editing the item.");
                return View("Edit", model);
            }

            TempData.AddMessage("Item edited successfully.");
            return RedirectToAction("Item", new { itemId = model.QMNoteId.ToString() });
        }

        private void SetTags()
        {
            var tags = Repository.GetIndex(includeHidden: false)
                .SelectMany(x => x.Tags)
                .Distinct()
                .OrderBy(x => x)
                .ToList();

            ViewData["ExistingTags"] = tags;
        }
    }
}

FisCompendium.Web/Views/Shared/_Layout.cshtml
@using System.Security.Claims
@using FisCompendium.Data.User_Data
@using FisCompendium.Web.Extensions
@{
    var Username = User?.Identity?.Name ?? "Guest";
    var LoggedIn = Username != "Guest";
    var IsQM = User.HasClaim(ClaimTypes.Role, PermissionsLevel.QM.ToString());
    var HasMessages = TempData.GetMessages().Any();
    var HasErrors = TempData.GetErrors().Any();
    var CurrentUrlPath = Context.Request.Path + "/" + Context.Request.QueryString;

    var AcceptedTAC = Context.Request.Cookies["AcknowledgedTAC"] != null;
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="robots" content="noindex,nofollow" />
    <title>Legacy of the Goddess</title>
    <link rel="shortcut icon" href="~/favicon.ico" />

    @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/jquery-ui/themes/smoothness/jquery-ui.min.css" asp-append-version="true">
    <link rel="stylesheet" href="~/lib/tag-it/css/jquery.tagit.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/theme.min.css" asp-append-version="true" />*@
    <link rel="stylesheet" href="~/css/site.bundle.min.css" />

    @*<script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation/dist/additional-methods.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.min.js" asp-append-version="true"></script>
    <script src="~/lib/popper.js/dist/umd/popper.min.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-ui/jquery-ui.min.js" asp-append-version="true"></script>
    <script src="~/lib/tag-it/js/tag-it.js" asp-append-version="true"></script>*@
    <script src="~/js/site.bundle.min.js"></script>
</head>
<body>
    <div class="topleft">
        <span class="navbar-brand">Fi’s Compendium</span>
        <br />
        <div class="dropdown" align="left" style="margin: 5px 0 0 10px">
            <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                <span>Navigation</span>
            </button>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                <li>@Html.ActionLink("Story", "Index", "Story")</li>
                @*<li>@Html.ActionLink("Status", "Index", "Status")</li>*@
                <li>@Html.ActionLink("Map", "Local", "Map")</li>
                <li>@Html.ActionLink("Knowledge", "Index", "Knowledge")</li>
                <li>@Html.ActionLink("Players", "Index", "PlayerLog")</li>
                <li>@Html.ActionLink("About", "Index", "Home")</li>
            </ul>
        </div>
        @if (IsQM)
        {
            <div class="dropdown" style="margin: -40px 0 0 115px">
                <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu3" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                    <span>QM Tools</span>
                </button>
                <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                    <li>@Html.ActionLink("Notes", "Index", "QMNotes")</li>
                    <li>@Html.ActionLink("QM Maps", "World", "QMMaps")</li>
                    <li>@Html.ActionLink("Player Points", "Update", "PlayerPoints")</li>
                    <li>@Html.ActionLink("Set Permissions", "Update", "Permissions")</li>
                    <li>@Html.ActionLink("Hex Grid", "Grid", "Combat")</li>
                    <li>@Html.ActionLink("Combat Tools", "Tools", "Combat")</li>
                </ul>
            </div>
        }
    </div>
    <div class="topright">
        <span class="navbar-brand">Welcome, @Username</span>
        <br />
        <div class="dropdown" align="right" style="margin: 5px 10px 0 0">
            <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span>Account</span>
            </button>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenu2">
                @if (LoggedIn)
                {
                    <li>@Html.ActionLink("Change Password", "ChangePassword", "Account")</li>
                    <li>@Html.ActionLink("Change Email", "ChangeEmail", "Account")</li>
                    <li>@Html.ActionLink("Update Preferences", "UpdatePreferences", "Account")</li>
                    <li>@Html.ActionLink("Logout", "Logout", "Account")</li>
                }
                else
                {
                    <li>@Html.ActionLink("Login", "Login", "Account", new { lastPage = CurrentUrlPath }, htmlAttributes: null)</li>
                    <li>@Html.ActionLink("Register", "Register", "Account", new { lastPage = CurrentUrlPath }, htmlAttributes: null)</li>
                }
            </ul>
        </div>
    </div>
    <div class="container-fluid bodycontent">
        
        @if(!LoggedIn && !AcceptedTAC)
        { 
            <div class="panel-primary collapse show" style="margin-top: 10px; margin-bottom: 20px" id="tac-panel">
                <button id="acknowledgeTAC" class="close btn btn-secondary" type="button" data-toggle="collapse" data-target="#tac-panel" aria-expanded="false">
                    <span size="12">&times;</span>
                </button>
                <div class="panel-heading">
                    <strong>NOTICE:</strong> By using this site, you agree to the <a href="/Home/TAC" target="_blank"><u>Terms and Conditions</u></a>.
                </div>
            </div>
        }

        @if (HasMessages)
        {
            <div class="panel-info collapse show" id="messages-panel">
                <button class="close btn btn-secondary" type="button" data-toggle="collapse" data-target="#messages-panel" aria-expanded="false">
                    <span size="12">&times;</span>
                </button>
                <div class="panel-heading">
                    <strong>Note:</strong>
                </div>
                <div class="panel-body">
                    <ul>
                        @foreach (var msg in TempData.GetMessages())
                        {
                            <li>@msg</li>
                        }
                    </ul>
                </div>
            </div>
        }
        <div class="panel panel-default">
            <div class="panel-heading">
                <h2>@ViewData["Title"]</h2>
            </div>
            <div class="panel-body">
                @if (HasErrors)
                {
                    <div class="container-fluid">
                        <div class="panel-danger">
                            <div class="panel-heading">
                                <strong>Errors:</strong>
                            </div>
                            <div class="panel-body">
                                <ul>
                                    @foreach (var error in TempData.GetErrors())
                                    {
                                        <li>@error</li>
                                    }
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="container-fluid">
                        @RenderBody()
                    </div>
                }
                else
                {
                    @RenderBody()
                }
            </div>
        </div>
    </div>

    @RenderSection("Scripts", required: false)
    <script type="text/javascript">
        $(document).ready(function() {
            $('#acknowledgeTAC').click(function () {
                var exdate = new Date();
                exdate.setDate(exdate.getDate() + 60);
                var c_value = "true; expires=" + exdate.toUTCString();
                document.cookie = "AcknowledgedTAC" + "=" + c_value;
            });
        });
    </script>
</body>
</html>