FisCompendium.Web/Controllers/KnowledgeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Text.RegularExpressions;
using FisCompendium.Data.Game_Data;
using FisCompendium.Web.Extensions;
using FisCompendium.Web.Utilities.GameData.Knowledge;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace FisCompendium.Web.Controllers
{
    public class KnowledgeController : Controller
    {
        private IKnowledgeRepository Repository { get; }

        public KnowledgeController(IKnowledgeRepository repository)
        {
            Repository = repository;
        }

        public IActionResult Error() => View();

        public IActionResult Index([FromQuery]bool showAll)
        {
            var index = Repository.GetIndex(showAll);
            return View(index);
        }

        public IActionResult Item([FromQuery] string itemId, [FromQuery] string title = "")
        {
            if (!Guid.TryParse(itemId, out var id))
            {
                TempData.AddError("Id could not be parsed.");
                return RedirectToAction("Index");
            }

            var data = Repository.GetById(id);
            if (data == null)
            {
                TempData.AddError("Item not found.");
                return RedirectToAction("Index");
            }

            data.Item.Data = ParseLinks(data.Item.Data);

            return View("Item", data);
        }

        private IEnumerable<string> GetSubStrings(string input, string start, string end)
        {
            Regex r = new Regex(Regex.Escape(start) + "(.*?)" + Regex.Escape(end));
            MatchCollection matches = r.Matches(input);
            foreach (Match match in matches)
                yield return match.Groups[1].Value;
        }

        private string ParseLinks(string input)
        {
            if (string.IsNullOrEmpty(input)) return input;
            var replacements = GetSubStrings(input, "[[", "]]")
                .Select(x => $"[[{x}]]")
                .ToList();
            if (!replacements.Any()) return input;

            string output = input + "";
            foreach (var replacement in replacements)
            {
                var title = replacement.Replace("[[", "").Replace("]]", "");
                var id = Repository.GetItemId(title);
                var item = Repository.GetById(id);

                if (id == Guid.Empty)
                {
                    var url = Url.Action("NewByTitle");
                    var html = $"<a href='{url}?title={WebUtility.UrlEncode(title)}' style='color: red' target='_blank'>{title}</a>";
                    output = output.Replace(replacement, html);
                }
                else
                {
                    var url = Url.Action("Item");
                    var html = $"<a href='{url}?itemId={id}'>{title}</a>";
                    output = output.Replace(replacement, html);
                }
            }

            return output;
        }

        [Authorize(Roles = "QM, TrustedPlayer")]
        public IActionResult NewByTitle([FromQuery] string title)
        {
            SetTags();

            return View("New", new KnowledgeItem
            {
                Title = title,
            });
        }

        [Authorize(Roles="QM, TrustedPlayer")]
        public IActionResult New(KnowledgeItem model)
        {
            SetTags();

            if (model == null)
            {
                model = new KnowledgeItem();
                return View(model);
            }

            if (!ModelState.IsValid)
            {
                TempData.AddError("Please correct validation errors.");
                return View(model);
            }

            model.Editor = User?.Identity?.Name ?? "Guest";

            var id = Repository.Create(model);
            if (id == Guid.Empty)
            {
                TempData.AddError("An error occurred while creating the item.");
                return View(model);
            }

            TempData.AddMessage("Item created successfully.");
            return RedirectToAction("Item", new {itemId = id.ToString()});
        }

        [Authorize(Roles = "QM, TrustedPlayer")]
        public IActionResult Edit([FromQuery] string itemId)
        {
            SetTags();

            if (!Guid.TryParse(itemId, out var id))
            {
                TempData.AddError("Id could not be parsed.");
                return RedirectToAction("Index");
            }

            var data = Repository.GetById(id);
            if (data == null)
            {
                TempData.AddError("Item not found.");
                return RedirectToAction("Index");
            }

            return View(data.Item);
        }

        [Authorize(Roles = "QM, TrustedPlayer")]
        public IActionResult SubmitEdit(KnowledgeItem model)
        {
            SetTags();

            if (!ModelState.IsValid)
            {
                TempData.AddError("Please correct validation errors.");
                return View("Edit", model);
            }

            var data = Repository.GetById(model.KnowledgeItemId);
            if (data == null)
            {
                TempData.AddError("Item not found.");
                return RedirectToAction("Index");
            }

            model.Editor = User?.Identity?.Name ?? "Guest";

            var success = Repository.Edit(model);
            if (!success)
            {
                TempData.AddError("An error occurred while editing the item.");
                return View("Edit", model);
            }

            TempData.AddMessage("Item edited successfully.");
            return RedirectToAction("Item", new { itemId = model.KnowledgeItemId.ToString() });
        }

        public IActionResult SubmitComment(KnowledgeItemComment model)
        {
            if (!ModelState.IsValid)
            {
                TempData.AddError("Comment is too short.");
                return RedirectToAction("Item", new { itemId = model.KnowledgeItemId.ToString() });
            }

            var data = Repository.GetById(model.KnowledgeItemId);
            if (data == null)
            {
                TempData.AddError("Item not found.");
                return RedirectToAction("Index");
            }

            var username = User?.Identity?.Name ?? "Guest";
            if (username == "Guest")
            {
                TempData.AddError("You must register or login before commenting.");
                return RedirectToAction("Login", "Account");
            }

            model.Username = username;

            var success = Repository.SubmitComment(model);
            if (!success)
            {
                TempData.AddError("An error occurred while submitting the edit request.");
            }
            else
            {
                TempData.AddMessage("Comment added.");
            }

            return RedirectToAction("Item", new { itemId = model.KnowledgeItemId.ToString() });
        }

        private void SetTags()
        {
            var tags = Repository.GetIndex(includeHidden: false)
                .SelectMany(x => x.Tags)
                .Distinct()
                .OrderBy(x => x)
                .ToList();

            ViewData["ExistingTags"] = tags;
        }
    }
}

FisCompendium.Web/Views/Knowledge/Edit.cshtml
@using System.Security.Claims
@using FisCompendium.Data.User_Data
@using Newtonsoft.Json
@model FisCompendium.Data.Game_Data.KnowledgeItem;
@{
    ViewBag.Title = "Knowledge Compendium";

    var existingTags = ViewData["ExistingTags"] as List<string> ?? new List<string>();

    var formControl = new {@@class = "form-control", autocomplete = "off"};
    var textControl = new {@@class = "form-control", autocomplete = "off", rows="12"};
}

@using (Html.BeginForm("SubmitEdit", "Knowledge"))
{
    @Html.HiddenFor(x => x.KnowledgeItemId)
    <div class="text-center">
        <div class="row" style="margin-bottom: 0px">
            <div class="col-md-1">
                <h4 class="float-right">Title:</h4>
            </div>
            <div class="col-md-8">
                @Html.HiddenFor(x => x.Title)
                <div class="float-left"><h4>@Model.Title</h4></div>
            </div>
            <div class="col-md-3 text-danger">
                @Html.ValidationMessageFor(x => x.Title)
            </div>
        </div>
        <div class="row">
            <div class="col-md-1">
                <h4 class="float-right">Tags:</h4>
            </div>
            <div class="col-md-8">
                @Html.TextBoxFor(x => x.TagsRaw, formControl)
            </div>
            <div class="col-md-3 text-danger">
                @Html.ValidationMessageFor(x => x.TagsRaw)
            </div>
        </div>
        <div class="row" style="margin-top: -8px">
            <div class="col-md-1">
                <h4 class="float-right">Data:</h4>
            </div>
            <div class="col-md-8">
                @Html.TextAreaFor(x => x.Data, textControl)
            </div>
            <div class="col-md-3 text-danger">
                @Html.ValidationMessageFor(x => x.Data)
            </div>
        </div>
        <div class="row">
            <div class="col-md-1">&nbsp;</div>
            <div class="col-md-1">
                <div class="float-left">
                    @Html.CheckBoxFor(x => x.Archived, textControl)
                    <h4>Archive?</h4>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <input type="submit" class="btn btn-primary float-right" style="margin-top: 15px" />        
            </div>
        </div>
    </div>
}
<hr/>
<h2>Data Preview:</h2>
<div class="well well-sm" id="preview"></div>

<script type="text/javascript" src="~/lib/showdownjs/showdown.min.js" asp-append-version="true"></script>
<script type="text/javascript">

    function init() {
        var converter = new showdown.Converter();

        var text = $('#Data').val();
        var text_html = converter.makeHtml(text);
        $("#preview").html(text_html);
    }

    $(document).ready(function () {

        init();

        $('#Data').keyup(function () {
            var text = $('#Data').val();
            var converter = new showdown.Converter();
            var text_html = converter.makeHtml(text);
            $("#preview").html(text_html);
        });

        $("#TagsRaw").tagit({
            fieldName: "TagsRaw",
            availableTags: @Html.Raw(JsonConvert.SerializeObject(existingTags)),
            caseSensitive: false
        });
    });
</script>

FisCompendium.Web/Views/Knowledge/Index.cshtml
@using System.Security.Claims
@using FisCompendium.Data.Game_Data;
@using FisCompendium.Data.User_Data
@using Newtonsoft.Json

@model List<KnowledgeItemIndex>
@{
    ViewBag.Title = "Knowledge Compendium";

    var IsQM = User.HasClaim(ClaimTypes.Role, PermissionsLevel.QM.ToString());
    var IsTrustedPlayer = User.HasClaim(ClaimTypes.Role, PermissionsLevel.TrustedPlayer.ToString());
    var Username = User?.Identity?.Name ?? "Guest";
    var LoggedIn = Username != "Guest";

    var preferredSearchView = Context.Request.Cookies["PreferredSearchView"] ?? "list";
    var listViewActive = preferredSearchView == "list" ? "active" : "";
    var conditionalHideListView = preferredSearchView != "list" ? "display: none" : "";
    var categoryViewActive = preferredSearchView != "list" ? "active" : "";
    var conditionalHideCategoryView = preferredSearchView == "list" ? "display: none" : "";
}

<div style="min-height: 1000px">
    <div class="text-center">
        @if (IsQM || IsTrustedPlayer)
        {
            <div>
                @Html.ActionLink("New Entry", "New", new { }, new { @class = "btn btn-primary", target = "_blank" })
            </div>
        }
        else if (LoggedIn)
        {
            <div>
                <div class="panel-warning collapse show" style="margin-top: 10px; margin-bottom: 20px" id="index-panel">
                    <button id="close" class="close btn btn-secondary" type="button" data-toggle="collapse" data-target="#index-panel" aria-expanded="false">
                        <span size="12">&times;</span>
                    </button>
                    <div class="panel-heading">
                        <strong>Note:</strong> If you’d like to contribute to maintaining these entries, just ask in the discord channel to have your permissions elevated.
                    </div>
                </div>
            </div>
        }
        <div style="display: block; width: 100%">
            <span style="font-size: 36px;">&#x2315;</span>
            <input type="text" id="searchString" placeholder="Comma, Delimited, Search" style="min-width: 315px; height: 35px"><br />
        </div>
        <div>
            <ul class="nav nav-pills">
                <li id="list-view" class="@listViewActive">
                    <a href="#">List View</a>
                </li>
                <li id="category-view" class="@categoryViewActive">
                    <a href="#">Category View</a>
                </li>
            </ul>
        </div>
    </div>
    
    <hr />

    <div id="search-results" style="width: 100%; @conditionalHideListView">
        @foreach (var item in Model)
        {
            var lockText = item.Archived ? "&#128274; (Archived)" : "";
            <div id="item-@item.KnowledgeItemId" class="index-item" data-title="@item.Title" data-tags="@item.TagsRaw" data-score="0">
                <a href="/Knowledge/Item?itemId=@item.KnowledgeItemId&title=@Html.UrlEncoder.Encode(item.Title)" style="color: #A0C0D0; font-weight: bold"><h4>&rArr; @Html.Raw(lockText) @item.Title</h4></a>
                <h5>@item.TagsRaw.Replace(",", ", ")</h5>
            </div>
        }
    </div>
    <div id="category-results" style="width: 100%; @conditionalHideCategoryView"></div>
</div>

<script type="text/javascript">
    function DoSearch(text) {
        //Score each entry based on title, tag hits
        $("#search-results").find(".index-item").each(function (i, ele) {
            var score = 0;
            var searchTerms = text.split(",");
            searchTerms.forEach(function (term) {
                term = term.trim();

                //Title matches
                var title = $(ele).data("title").toLowerCase();
                if (title === term) score += 5;
                else if (title.indexOf(term) >= 0 || term.indexOf(title) >= 0) score += 1;

                //Tag matches
                var tags = $(ele).data("tags").toLowerCase().split(',');
                tags.forEach(function (tag) {
                    tag = tag.trim();
                    if (tag.toLowerCase() === term.toLowerCase()) score += 5;
                    else if (tag.indexOf(term) >= 0) score += 1;
                });
            });
            $(ele).attr("data-score", score);
        });

        //Order entries
        var items = $('#search-results').find(".index-item");
        items.sort(function (a, b) {
            var scoreA = parseInt($(a).attr('data-score'));
            var scoreB = parseInt($(b).attr('data-score'));
            return (scoreA < scoreB) ? 1 : (scoreA > scoreB) ? -1 : 0;
        });
        $('#search-results').html(items);

        //Hide entries with score = 0
        $('#search-results').find(".index-item").each(function (i, ele) {
            $(ele).show();
            var score = $(ele).data("score");
            if (score === 0) $(ele).hide();
        });
    }

    function UpdateCategoryView() {
        //Get list of tags
        var tagsRaw = "";
        $('#search-results').find('.index-item').filter(function() {
            return $(this).css("display") !== "none";
        }).each(function (i, ele) {
            tagsRaw += $(ele).data("tags").toLowerCase() + ',';
        });

        //remove duplicates (it's already ordered by search score)
        var tags = tagsRaw.split(',');
        var uniqueTags = [];
        $.each(tags, function (i, tag) {
            if (tag.length > 0 && $.inArray(tag, uniqueTags) === -1) uniqueTags.push(tag);
        });

        //Clear category results
        $('#category-results').empty();

        //Build category view
        $.each(uniqueTags, function (i, tag) {
            var aggregateHtml = "";
            $('#search-results').find('.index-item').filter(function () {
                return $(this).css("display") !== "none";
            }).filter(function (n, item) {
                var eleTags = $(item).data("tags").toLowerCase();
                return eleTags.includes(tag);
            }).each(function(n, ele) {
                aggregateHtml += $(ele).find('a').prop('outerHTML');
            });

            $('#category-results').append("<details open><summary>" + tag + "</summary>" + aggregateHtml + "</details><br>");
        });
    }

    function setPreference(pref) {
        var exdate = new Date();
        exdate.setDate(exdate.getDate() + 3650);
        var c_value = pref + "; expires=" + exdate.toUTCString();
        document.cookie = "PreferredSearchView" + "=" + c_value;
    }

    function showListView() {
        $('#list-view').addClass('active');
        $('#category-view').removeClass('active');
        $('#category-results').fadeOut();
        $('#search-results').fadeIn();
        setPreference("list");
    }

    function showCategoryView() {
        $('#category-view').addClass('active');
        $('#list-view').removeClass('active');
        $('#search-results').fadeOut();
        $('#category-results').fadeIn();
        setPreference("category");
    }

    var lastText = "";
    $(document).ready(function () {
        $('#searchString').focus();
        $('#searchString').keyup(function () {
            var text = $('#searchString').val();
            if (text.length === 0) {

                var items = $('#search-results').find(".index-item");
                items.sort(function (a, b) {
                    var titleA = $(a).data('title');
                    var titleB = $(b).data('title');
                    return (titleA < titleB) ? -1 : (titleA > titleB) ? 1 : 0;
                });
                $('#search-results').html(items);

                $('#search-results').find(".index-item").each(function (i, ele) {
                    $(ele).show();
                });

                UpdateCategoryView();
            }
            if (text === lastText) return;
            if (text.length < 3) return;

            lastText = text;

            DoSearch(text.toLowerCase());
            UpdateCategoryView();
        });

        $('#list-view').click(showListView);
        $('#category-view').click(showCategoryView);

        UpdateCategoryView();
    });
</script>

FisCompendium.Web/Views/Knowledge/Item.cshtml
@using System.Security.Claims
@using FisCompendium.Data.User_Data
@model FisCompendium.Data.Game_Data.KnowledgeItemComposite

@{
    ViewBag.Title = "Knowledge Compendium";

    var IsTrustedPlayer = User.HasClaim(ClaimTypes.Role, PermissionsLevel.TrustedPlayer.ToString());

    var Username = User?.Identity?.Name ?? "Guest";

    var editorString = string.IsNullOrWhiteSpace(Model.Item.Editor) ? "" : $" by {Model.Item.Editor}";
}


<div class="panel panel-info">
    <div class="panel-heading">
        @if (IsTrustedPlayer)
        {
            <a href="/Knowledge/Edit?itemId=@Model.Item.KnowledgeItemId" style="font-weight: bold"><h4>&rArr; @Model.Item.Title</h4></a><h5>@Model.Item.TagsRaw.Replace(",", ", ")</h5>
        }
        else
        {
            <h4>@Model.Item.Title</h4> <h5>@Model.Item.TagsRaw.Replace(",", ", ")</h5>
        }
        @if (Model.Item.Archived)
        {
            <h6>&#128274; (Archived)</h6>
        }
    </div>
    <div>
        <div id="item-markup" class="well well-sm" style="width: 100%"></div>
        <div id="item-text" class="hidden">@Model.Item.Data</div>
    </div>
    <h5>&nbsp;Last edited on @(Model.Item.LastEdited + editorString)</h5>
</div>
<!--Player Notes-->
@if (Model.Comments.Any())
{
    <hr/>
    <div>
        <h4>Comments: </h4>
    </div>
    <div id="player-notes" style="margin-top: 15px; height: 100%; overflow-x: hidden;">
        @foreach (var comment in Model.Comments)
        {
            var now = DateTime.UtcNow;
            var noteCreated = DateTime.Parse(comment.DateCommented.Replace(" (UTC)", ""));
            string createdStr;
            if (noteCreated > now.AddMinutes(-2))
            {
                createdStr = "just now";
            }
            else if (noteCreated > now.AddHours(-1))
            {
                createdStr = (now - noteCreated).TotalMinutes.ToString("N0") + " minutes ago";
            }
            else if (noteCreated > now.AddDays(-2))
            {
                createdStr = (now - noteCreated).TotalHours.ToString("N0") + " hours ago";
            }
            else if (noteCreated > now.AddDays(-30))
            {
                createdStr = (now - noteCreated).TotalDays.ToString("N0") + " days ago";
            }
            else
            {
                createdStr = noteCreated.ToString("yyyy/MM/dd hh:mm tt") + " (UTC)";
            }

            <div class="player-note panel panel-primary">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-12">
                            <div style="margin-top: 5px; margin-left: 2px;">
                                <span style="font-size: larger; font-weight: bold;">@comment.Username</span>
                                <span style="font-size: smaller">(@createdStr)</span>
                            </div>
                        </div>
                    </div>
                </div>        
                <div class="row">
                    <div class="col-xs-12">
                        <div id="note-markdown-@comment.Id.AsObjectId" class="notes-markdown well well-sm" style="margin-bottom: 0px; padding-left: 25px; padding-right: 25px;"></div>
                        <textarea id="note-text-@comment.Id.AsObjectId" class="notes collapse" style="width: 100%; overflow-y: auto" rows="3">@comment.Comment</textarea>
                    </div>
                </div>
            </div>
        }
    </div>
}
<!--Add comment-->
<div id="comment-pane">
    @if (Username != "Guest")
    {
        using (Html.BeginForm("SubmitComment", "Knowledge"))
        {
            <input type="hidden" name="KnowledgeItemId" value="@Model.Item.KnowledgeItemId" />
            <textarea id="new-note-raw" name="Comment" placeholder="Add a comment..." class="form-control" onkeyup="updatePreview();" style="overflow-y: auto; resize: none; width: 100%" rows="5"></textarea>
            <br />
            <div id="new-note-details">
                <ul>
                    <li>Supports basic html and/or markdown, specifically <a href="http://demo.showdownjs.com/" target="_blank">showdownjs</a>.</li>
                    <li>Do not abuse this. You will be banned.</li>
                </ul><br />
            </div>
            <div id="new-note-markdown-container" class="collapse">
                <div class="row">
                    <div class="col" style="margin-top: -2px; margin-bottom: -3px;">
                        <h6 class="pull-left"><a href="http://demo.showdownjs.com/" target="_blank">Formatting Guide</a></h6>
                        <input type="submit" class="btn btn-primary pull-right" />
                    </div>
                </div>
                <h4>Preview:</h4>
                <div id="new-note-markdown" class="well well-sm" style="max-height: 150px; overflow-y: auto;"></div>
            </div>
        }
    }
</div>


<script type="text/javascript" src="~/lib/showdownjs/showdown.min.js" asp-append-version="true"></script>
<script type="text/javascript">
    $(document).ready(function () {
        var converter = new showdown.Converter();

        var text = $('#item-text').text();
        var text_html = converter.makeHtml(text);
        $('#item-markup').html(text_html);

        var text_qm = $('#item-qm-text').text();
        var text_html_qm = converter.makeHtml(text_qm);
        $('#item-qm-markup').html(text_html_qm);

        var player_notes_group = $('#player-notes');
        player_notes_group.children().each(function (i, player_note) {
            var notes = $(player_note).find('.notes').val();
            var notes_html = converter.makeHtml(notes);
            $(player_note).find('.notes-markdown').html(notes_html);
        });
    });

    var converter = new showdown.Converter();
    function updatePreview() {
        $('#new-note-markdown-container').show();
        $('#new-note-details').hide();

        var text_raw = $('#new-note-raw').val();
        var text_html = converter.makeHtml(text_raw);

        $('#new-note-markdown').html(text_html);
    }
</script>

FisCompendium.Web/Views/Knowledge/New.cshtml
@using System.Security.Claims
@using FisCompendium.Data.User_Data
@using Newtonsoft.Json

@model FisCompendium.Data.Game_Data.KnowledgeItem;
@{
    ViewBag.Title = "Knowledge Compendium";

    var existingTags = ViewData["ExistingTags"] as List<string> ?? new List<string>();

    var formControl = new { @@class = "form-control", autocomplete = "off" };
    var textControl = new { @@class = "form-control", autocomplete = "off", rows = "12" };
}

@using (Html.BeginForm("New", "Knowledge"))
{
    <div class="text-center">
        <div class="row" style="margin-bottom: 0px">
            <div class="col-md-1">
                <h4 class="float-right">Title:</h4>
            </div>
            <div class="col-md-8">
                @Html.TextBoxFor(x => x.Title, formControl)
            </div>
            <div class="col-md-3 text-danger">
                @Html.ValidationMessageFor(x => x.Title)
            </div>
        </div>
        <div class="row">
            <div class="col-md-1">
                <h4 class="float-right">Tags:</h4>
            </div>
            <div class="col-md-8">
                @Html.TextBoxFor(x => x.TagsRaw, formControl)
            </div>
            <div class="col-md-3 text-danger">
                @Html.ValidationMessageFor(x => x.TagsRaw)
            </div>
        </div>
        <div class="row" style="margin-top: -8px">
            <div class="col-md-1">
                <h4 class="float-right">Data:</h4>
            </div>
            <div class="col-md-8">
                @Html.TextAreaFor(x => x.Data, textControl)
            </div>
            <div class="col-md-3 text-danger">
                @Html.ValidationMessageFor(x => x.Data)
            </div>
        </div>

        <div class="row">
            <div class="col-md-1">&nbsp;</div>
            <div class="col-md-1">
                <div class="float-left">
                    @Html.CheckBoxFor(x => x.Archived, textControl)
                    <h4>Archive?</h4>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <input type="submit" class="btn btn-primary float-right" style="margin-top: 15px" />
            </div>
        </div>
    </div>
}
<hr />
<h3>Data Preview:</h3>
<div class="well well-sm" id="preview"></div>

<script type="text/javascript" src="~/lib/showdownjs/showdown.min.js" asp-append-version="true"></script>
<script type="text/javascript">
    $(document).ready(function() {
        $('#Data').keyup(function () {
            var text = $('#Data').val();
            var converter = new showdown.Converter();
            var text_html = converter.makeHtml(text);
            $("#preview").html(text_html);
        });

        $("#TagsRaw").tagit({
            fieldName: "TagsRaw",
            availableTags: @Html.Raw(JsonConvert.SerializeObject(existingTags)),
            caseSensitive: false
        });
    });
</script>